### ISSUE TITLE
Replace ntp with timedatectl 

### ISSUE THREAD

**Issue by whoamin** [MatMoul/archdi-pkg#1]
options+=("ntp" "Client NTP for clock sync" on)

Better way use systemd tools for this, example:
timedatectl set-timezone Europe/Moscow
timedatectl set-ntp true (I dont realy know it's TRUE by default or not)

also LXQt should install aur/plataro-icons (or oxygen-icons) as minimum

> The recommended login manager for LXQt is sddm
> https://wiki.archlinux.org/index.php/LXQt
> https://wiki.manjaro.org/index.php?title=Minimal_LXQt_installation

**Comment by MatMoul** [comment]
ntp will be moved later in a systemd config menu with other features.
LXQT need more work but Plasma 5 is a proiority at this time.
Issue still open until these changes are included.

**Comment by MatMoul** [comment]
New version include LXQt changes.

**Comment by MatMoul** [comment]
I've now disabled ntp by default...
timedatectl is available in config/systemd/timedatectl menu...
