### ISSUE TITLE
Add bluetooth manager (blueman or blueberry) option

### ISSUE THREAD

**Issue by spsf64** [MatMoul/archdi-pkg#24]
Maybe this is a good addition?
I also noticed that bluetooth service was not started (I selected it and packages were installed) in my cinnamon install, not sure if I did something wrong...
I have to do another new installation to "master" your scripts, lol!
Once again thanks for this great project!

**Comment by MatMoul** [comment]
@spsf64 I'm not sure I've fully replly to your question...
Now bluez (it'is the base) and enabling the bluetooth service, is handled.
But for blueman and blueberry, I don't know them...
I use Plasma5 that have is own bluetooth manager.
blueman and blueberry are GTK app...
If you seem this is good to add it to some GTK desktop, your free to purpose PR (one per DE) or if you don't have time or dev knowless, return me here what can be good for GTK or more specific DE.

**Comment by spsf64** [comment]
> @spsf64 I'm not sure I've fully replly to your question...
> Now bluez (it'is the base) and enabling the bluetooth service, is handled.
> But for blueman and blueberry, I don't know them...
> I use Plasma5 that have is own bluetooth manager.
> blueman and blueberry are GTK app...
> If you seem this is good to add it to some GTK desktop, your free to purpose PR (one per DE) or if you don't have time or dev knowless, return me here what can be good for GTK or more specific DE.

@MatMoul just installed again, Bluetooth is working 100%! 
I used blueman and it loads just after DE login (cinnamon).
I think you can close this issue.
Thank you!

**Comment by MatMoul** [comment]
@spsf64 Thanks for return, I close the issue...
