### ISSUE TITLE
systemd-resolved service

### ISSUE THREAD

**Issue by wolfshirts** [MatMoul/archdi-pkg#26]
After installing I was unable to resolve certain hosts, archlinux.org for example. In order to fix it, I had to:

> ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
> mkdir /etc/systemd/resolved.conf.d
> echo -e "[Resolve]\nDNSSEC=false" > /etc/systemd/resolved.conf.d/dnssec.conf

This was after using archfi, then accepting the option to transition to archdi without a reboot. I'm not sure if the issue lies upstream, or if it is in the installer.

**Comment by MatMoul** [comment]
I don't have any idea what's your problem...
As default when you install arch linux with archfi, the dhcpcd can be enabled. This work well for me.
When you launch archdi, you can install NetworkManager and you are asked to disable dhcpcd and enable NetworkManager. This work well for me too...
If you use an other configuration, can you best describe me your network configuration?

**Comment by wolfshirts** [comment]
I disabled dhcpd and enabled NM. In the selection for systemd-services I enabled resolved. I would have to go back through the install process to get a clearer bug report unfortunately.

**Comment by MatMoul** [comment]
Just launch archdi and disable resolved in Systemd - Services - Disable

**Comment by wolfshirts** [comment]
I disabled resolved with systemctl and stopped the service, which left me with no DNS resolution instead of the fallback resolution from resolved. Then I solved the issue with the commands listed in my initial post. I will spin up a VM and go through the install steps and see if I can reproduce the problem in order to provide you with a more helpful report.

**Comment by wolfshirts** [comment]
I was able to reproduce the issue.
**Steps:**
Boot from Arch Linux 2019.02.01
Partition drives
Install pacstrap base
……......Install……………
systemctl enable DHCPD
………………………..........
Install and run archdi
Install yay
Update keyring
Refresh pacman keys
Install console generic + vim
Install network tools (default)
Install kernel
    kernel default
    kernel headers

services
………………………………
boxes checked
* network manager
* openssh
* cronie
* xdg-user-dirs
* numlockon
* haveged
* intel-ucode

prompted start network manager at boot:
selected yes

disable dhcpd at boot:
selected yes
looked like there was a quick screen that said failed to disable dhcpd but it flashed by quickly.

Enabled rest of services
Install default filesystem
Install default sound
Install default xorg
Install default fonts
Install default plasma
Install kde full meta
systemctl enable sddm
config systemd services, enabled:
accounts
auditd
autofs
systemd-resolved
reboot

On reboot:
<img width="648" alt="screen shot 2019-02-19 at 4 28 28 pm" src="https://user-images.githubusercontent.com/43915195/53057242-745a6a80-3463-11e9-96e9-51e49ab7b233.png">
It works if I stop/disable systemd-resolved.service. However according to https://wiki.archlinux.org/index.php/NetworkManager NM works with resolved.

> systemd-resolved
> NetworkManager can use systemd-resolved as a DNS resolver and cache. Make sure that systemd-resolved is properly configured and that systemd-resolved.service is started before using it.

> systemd-resolved will be used automatically if /etc/resolv.conf is a symlink to /run/systemd/resolve/stub-resolv.conf, /run/systemd/resolve/resolv.conf or /usr/lib/systemd/resolv.conf.
> You can enable it explicitly by setting the dns= option in NetworkManager.conf(5):

On install resolv.conf is not a symbolic link. 
> $ file /etc/resolv.conf
> /etc/resolv.conf: ASCII text

Just symlinking resolv.conf doesn't fix the issue. I'm not sure if this is an upstream issue, or an issue with the installer itself not properly configuring resolv.conf/NM. I did notice that there is a resolv.conf and a resolv.conf.bak in /etc.

If you need more information I have a test system with the issue running.

**Comment by MatMoul** [comment]
@wolfshirts 

> config systemd services, enabled:
> systemd-resolved

Try an install without touching systemd service in config...
If you touch this part of archdi, you need know what you make...

**Comment by wolfshirts** [comment]
Fair enough.
