### ISSUE TITLE
sig keys problem/ suggestion

### ISSUE THREAD

**Issue by W54J04S07T** [MatMoul/archdi-pkg#3]
It might be a good idea to insert a 
pacman-key --refresh-keys ( or other command )
somewhere early on in the install procedure.
Last 6 weeks or so has seen a number of packages
with bad sigs.  Pretty much messes up this package.

**Comment by MatMoul** [comment]
Yes, it would be a good idea ...
I never experienced this problem because I update daily.
I place a TAG "enhancement" for a future release.

**Comment by W54J04S07T** [comment]
Thanks for this addition.
However, can you also enable some sort
of no signature checking option?

I ran the key update twice during a single archdi
session and STILL got bad keys... go figure.

**Comment by MatMoul** [comment]
I really struggle to understand, I've never met these key issues.
If I could replicate, that would be easier.
Can you tell me the procedure brings you to this?

**Comment by W54J04S07T** [comment]
As of about 45 minutes ago it was
the KDE-apps install that triggered this.

**Comment by MatMoul** [comment]
Very strange,
Can you give me a screenshot or a picture when you encounter this problem?

**Comment by W54J04S07T** [comment]
Figured out what the problem is...
Seems some packagers are updating their keys and sigs
but keeping filenames unchanged.  My local repo
doesn't pick up a new file unless it has a
new revision in the file name...  embarrassing.
OTOH, being able to turn off that sig check
would be really handy some days.

**Comment by MatMoul** [comment]
I have never encountered this problem ...
Perhaps select another servers in /etc/pacman.d/mirrorlist

**Comment by MatMoul** [comment]
Closing issue because no return
