### ISSUE TITLE
f2fs-tools missing from File System section

### ISSUE THREAD

**Issue by osmose99** [MatMoul/archdi-pkg#35]
Could it be possible to add f2fs-tools in the File System section with the dosfstools and the others? Archfi permit f2fs patitionning but there's this no module to be able to use this kind of partition in the archdi packager.

By the way, thanks for this script.. Really useful!

**Comment by MatMoul** [comment]
Thanks for your feedback update ;-)
As I say on the archfi issue you can make a PR, it's very easy, just one line on https://github.com/MatMoul/archdi-pkg/blob/master/install/system/filesystem
If you don't want make it, I will make it,...

**Comment by osmose99** [comment]
Sorry, I was not aware of what was a PR. Thanks for the precision and knowledge... It's done now.
