### ISSUE TITLE
"gnome-mpv" renamed to "celluloid"

### ISSUE THREAD

**Issue by spsf64** [MatMoul/archdi-pkg#37]
The menu at: archdi-pkg/install/apps/multimedia/videoplayer has to be fixed!

Package at: https://www.archlinux.org/packages/community/x86_64/celluloid/

**Comment by MatMoul** [comment]
Thanks for your issue, I've just see that gnome-mpv was unavaible from repo and aur...
You're free to make a PR

**Comment by MatMoul** [comment]
I've just published a new release with this change...
