### ISSUE TITLE
Unable to install yay, and choosing Swedish mirrors results in Greek mirrors being included as well.

### ISSUE THREAD

**Issue by roesz** [MatMoul/archdi-pkg#40]
Expected behaviour: 
Choosing to install yay shouldn't result in only dependencies being installed ; Choosing Swedish mirrors should not add Greeks ones as well.

Actual behaviour:
Yay is not installed, it errors out. (Same with other AUR-helpers as well) ; Greek mirrors are included in the Swedish mirrors.

**Comment by MatMoul** [comment]
I'm not sure I understood the issue.

Is it a mirror issue that is choosed in archfi ?
Is it an error when making yay with Swedish or Greek mirrors ?
Or other ?

**Comment by roesz** [comment]
When you select to use Swedish mirrors, some Greek ones are included in the list as well, specifically it seems to be a single one (I can't specify which atm, I'm about to go to sleep and my PC is off). Whether the issue of yay being non-installable has to with the selected mirrors I'm not sure of either, the issue just appeared out of nowhere 2 weeks ago or so. I will return with more details, but I really need to sleep right now. I can't really think straight atm...
