### ISSUE TITLE
Also add the option to use other shells for new users and allow you to select which groups to put new users in.

### ISSUE THREAD

**Issue by lan-vuhoang** [MatMoul/archdi-pkg#43]

**Comment by MatMoul** [comment]
Why also and two issues...

**Comment by lan-vuhoang** [comment]
> Why also and two issues...

So that it's linked with my previous issue.

**Comment by MatMoul** [comment]
Sorry, some times I'm a devil, it's just retoric :(
Try to make a simple title for an issue and a complement in the message.
With this, it's more easy to maintain the project and new features.
