### ISSUE TITLE
More customization options.

### ISSUE THREAD

**Issue by lan-vuhoang** [MatMoul/archdi-pkg#44]
archdi already has the Config tab, which give out a great deal of system customization, but what about desktop customization?
This is some of my favorites:
1. Papirus icon theme. It's flat, beautiful and support a lot of applications. Easily installed with the `papirus-icon-theme` package in the `community` repo.
2. Arc, Adapta, Plata and Zuki themes. Arc and Adapta has a package in the repo (`arc-gtk-theme` and `adapta-gtk-theme`) but Zuki need to be manually compiled. Plata need to be manually compiled too but madgrid make a repo for precompiled Plata theme: [https://github.com/madgrid/plata-theme-compiled](url)

**Comment by lan-vuhoang** [comment]
More favorites:
3. Pacman misc. options `VerbosePkgLists`, `Color`, `TotalDownloads` and `ILoveCandy`. The first 3 are commented in the file, but `ILoveCandy` isn't because it's like an Easter egg.

**Comment by mirh** [comment]
This starts to sound like feature creep tbh. I think wine already would be too much. 
I'd rather have *actually* useful (but usually not "known by their names") stuff like, I don't know, zramswap or earlyoom. Maybe android-udev too.
