### ISSUE TITLE
Pacmangui panel doesn't do anything

### ISSUE THREAD

**Issue by mirh** [MatMoul/archdi-pkg#45]
Maybe this?
https://github.com/MatMoul/archdi-pkg/blob/bcde1b681829d343e7617cd3cb1241fed7c8fab3/install/apps/pacmangui/pacmangui#L4-L5

**Comment by MatMoul** [comment]
This is aur package, do you have installed trizen or yay with archdi?

**Comment by mirh** [comment]
Mhh no.
