### ISSUE TITLE
Fuse renaming

### ISSUE THREAD

**Issue by JohnnyLeone** [MatMoul/archdi-pkg#5]
Since latest update it looks like the arch repo has changed his names for fuse in fuse2 e.g fuse3.

Thanks for your good work here.

**Comment by MatMoul** [comment]
Thank for the info
I just tested archdi and it work with fuse...
I checked packages webpage and fuse don't exist...
fuse2 and fuse3 are in testing...
I will wait but I need to follow when the change is effective...
If you want, you have time to fork the project and make a PR with these changes... 
/src/install/system/filesystem (Line 13)
I will merge it when working

**Comment by JohnnyLeone** [comment]
My mirrors doesn't provide the old fuse package anymore... 
But i have an eye on it and try to contribute the change.

**Comment by MatMoul** [comment]
Don't forget, you can test your fork with :
archdi -t JohnnyLeone master
or 
archdi -t JohnnyLeone test1
the last parameters is the branch of your fork.

**Comment by MatMoul** [comment]
Thank for your work
